### PR TITLE
[waker64] Panic When Overflowing in `fetch_sub()`

### PR DESCRIPTION
**Pull request by ppenna**
Description
-------------

This PR fixes https://github.com/demikernel/scheduler/issues/11.

Summary of Changes
------------------------

- Changed `Waker64::fetch_sub()` to return a `None` value when overflowing
- Changed `WakerPageRef::drop()` to ~log~ panic when doubling free due to subtraction overflow in `Waker64::fetch_sub()`
- Fixed concerned unit tests

Related PRs
--------------

- https://github.com/demikernel/scheduler/pull/12

### CODE REVIEW

**Comment by BrianZill** [comment]
This looks okay to be, although I don't really know anything about the waker code.

One question: is this panic you're turning into a log message a logic error (i.e. a "should never happen") or is it an extraordinary situation (i.e. "unlikely to happen").  I assume it's not a "could easily happen".

**Comment by anandbonde** [comment]
> This looks okay to be, although I don't really know anything about the waker code.
> 
> One question: is this panic you're turning into a log message a logic error (i.e. a "should never happen") or is it an extraordinary situation (i.e. "unlikely to happen"). I assume it's not a "could easily happen".

Continuing on this thought, if this is something rare, we should think about the following:

1. Is this state recoverable? What is the loss if we just continue after logging?
2. How will the application using Demikernel detect this situation? What can it do if it does? Does it need to know?
3. If this is going to lead to other complex issues in future, we should just keep the panic in place instead?

**Comment by ppenna** [comment]
> > This looks okay to be, although I don't really know anything about the waker code.
> > One question: is this panic you're turning into a log message a logic error (i.e. a "should never happen") or is it an extraordinary situation (i.e. "unlikely to happen"). I assume it's not a "could easily happen".
> 
> Continuing on this thought, if this is something rare, we should think about the following:
> 
> 1. Is this state recoverable? What is the loss if we just continue after logging?
> 2. How will the application using Demikernel detect this situation? What can it do if it does? Does it need to know?
> 3. If this is going to lead to other complex issues in future, we should just keep the panic in place instead?

1. No it is not. This situation happens when a coroutine is double free.
2. This is not something that the application may "detect". If we double free, Demikernel will either crash without further warning or it will loop forever in the scheduler state silently.
3. Although the double free is non recoverable, it does not mean that it will lead to a crash / malfunctioning. It is highly dependent on what co-routine was badly programmed. For this reason, it is better to log the event.

**Comment by BrianZill** [comment]
> > > One question: is this panic you're turning into a log message a logic error (i.e. a "should never happen") or is it an extraordinary situation (i.e. "unlikely to happen"). I assume it's not a "could easily happen".
> > 
> > 
> > Continuing on this thought, if this is something rare, we should think about the following:
> > 
> > 1. Is this state recoverable? What is the loss if we just continue after logging?
> > 2. How will the application using Demikernel detect this situation? What can it do if it does? Does it need to know?
> > 3. If this is going to lead to other complex issues in future, we should just keep the panic in place instead?
> 
> 1. No it is not. This situation happens when a coroutine is double free.
> 2. This is not something that the application may "detect". If we double free, Demikernel will either crash without further warning or it will loop forever in the scheduler state silently.
> 3. Although the double free is non recoverable, it does not mean that it will lead to a crash / malfunctioning. It is highly dependent on what co-routine was badly programmed. For this reason, it is better to log the event.

Are these co-routines provided by us, or the "user" application?  If these co-routines are all internal to Demikernel, meaning that the "bad" programming that caused this error was our own, then a panic might be more appropriate.  We're more likely to catch it quickly and fix it faster.

**Comment by ppenna** [comment]
> > > > One question: is this panic you're turning into a log message a logic error (i.e. a "should never happen") or is it an extraordinary situation (i.e. "unlikely to happen"). I assume it's not a "could easily happen".
> > > 
> > > 
> > > Continuing on this thought, if this is something rare, we should think about the following:
> > > 
> > > 1. Is this state recoverable? What is the loss if we just continue after logging?
> > > 2. How will the application using Demikernel detect this situation? What can it do if it does? Does it need to know?
> > > 3. If this is going to lead to other complex issues in future, we should just keep the panic in place instead?
> > 
> > 
> > 
> > 1. No it is not. This situation happens when a coroutine is double free.
> > 2. This is not something that the application may "detect". If we double free, Demikernel will either crash without further warning or it will loop forever in the scheduler state silently.
> > 3. Although the double free is non recoverable, it does not mean that it will lead to a crash / malfunctioning. It is highly dependent on what co-routine was badly programmed. For this reason, it is better to log the event.
> 
> Are these co-routines provided by us, or the "user" application? If these co-routines are all internal to Demikernel, meaning that the "bad" programming that caused this error was our own, then a panic might be more appropriate. We're more likely to catch it quickly and fix it faster.

Sure. I changed the code as requested.

**Review by BrianZill — APPROVED** [review]
Looks great, ship it!

**Pull request merged**
